// Popular Indian colleges/universities. Users can type any value freely;
// this list powers autocomplete suggestions and the browse filter.
export const COLLEGES: string[] = [
  "IIT Madras",
  "IIT Bombay",
  "IIT Delhi",
  "IIT Kanpur",
  "IIT Kharagpur",
  "IIT Roorkee",
  "IIT Guwahati",
  "IIT Hyderabad",
  "IIT BHU",
  "IIIT Hyderabad",
  "IIIT Bangalore",
  "BITS Pilani",
  "BITS Goa",
  "BITS Hyderabad",
  "NIT Trichy",
  "NIT Warangal",
  "NIT Surathkal",
  "NIT Calicut",
  "NIT Rourkela",
  "VIT Vellore",
  "VIT Chennai",
  "SRM Chennai",
  "Manipal Institute of Technology",
  "Delhi University",
  "JNU Delhi",
  "Jamia Millia Islamia",
  "Jadavpur University",
  "Anna University",
  "PSG Tech Coimbatore",
  "PES University Bangalore",
  "RV College Bangalore",
  "MS Ramaiah Bangalore",
  "COEP Pune",
  "VJTI Mumbai",
  "Christ University Bangalore",
  "Symbiosis Pune",
  "IIM Ahmedabad",
  "IIM Bangalore",
  "IIM Calcutta",
  "AIIMS Delhi",
  "NLSIU Bangalore",
];
